"""baseline schema (Epic F1) — generated by scripts/gen_pg_baseline.py

Materializes the EXACT current effective SQLite schema (SCHEMA + every
MIGRATIONS column + all indexes) as equivalent Postgres DDL. Regenerate with
scripts/gen_pg_baseline.py whenever a MIGRATIONS column is added; add the
matching future revision (never edit this baseline in place after first ship).

The FTS5 mem_fts virtual table is intentionally absent — Postgres retrieval
degrades to absent (fts_enabled=False), out of scope for F1.

Revision ID: 0001_baseline
Revises:
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

BASELINE_DDL = """
CREATE TABLE IF NOT EXISTS admin_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL,
    target text NOT NULL DEFAULT '',
    detail text DEFAULT '',
    actor text DEFAULT '',
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS api_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    name text NOT NULL DEFAULT '',
    token_hash text NOT NULL UNIQUE,
    prefix_hint text NOT NULL DEFAULT '',
    scopes text NOT NULL DEFAULT '',
    created_at double precision NOT NULL,
    last_used_at double precision,
    expires_at double precision,
    revoked_at double precision
);

CREATE TABLE IF NOT EXISTS app_config (
    key text,
    value text NOT NULL,
    updated_at double precision NOT NULL,
    PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS artifact_state (
    job_id text NOT NULL,
    artifact text NOT NULL,
    subtask_id text DEFAULT '',
    synced_hash text DEFAULT '',
    flags text DEFAULT '',
    content text NOT NULL DEFAULT '',
    PRIMARY KEY (job_id, artifact)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at double precision NOT NULL,
    actor text NOT NULL DEFAULT '',
    actor_kind text NOT NULL DEFAULT '',
    action text NOT NULL,
    scope text NOT NULL DEFAULT 'instance',
    workspace_id bigint,
    job_id text NOT NULL DEFAULT '',
    target text NOT NULL DEFAULT '',
    channel text NOT NULL DEFAULT '',
    detail text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS auth_oidc_txn (
    state text,
    nonce text NOT NULL,
    redirect_after text NOT NULL DEFAULT '/',
    provider text NOT NULL DEFAULT 'oidc',
    created_at double precision NOT NULL,
    PRIMARY KEY (state)
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token_hash text,
    user_id bigint NOT NULL,
    created_at double precision NOT NULL,
    expires_at double precision NOT NULL,
    last_seen double precision NOT NULL,
    PRIMARY KEY (token_hash)
);

CREATE TABLE IF NOT EXISTS autonomy_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint,
    project text DEFAULT '',
    stage bigint,
    job_id text DEFAULT '',
    kind text NOT NULL,
    detail text DEFAULT '',
    actor text DEFAULT '',
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS autonomy_pins (
    workspace_id bigint NOT NULL,
    stage bigint NOT NULL,
    pin text NOT NULL,
    set_by text NOT NULL DEFAULT '',
    set_at double precision NOT NULL,
    PRIMARY KEY (workspace_id, stage)
);

CREATE TABLE IF NOT EXISTS autonomy_scores (
    workspace_id bigint NOT NULL,
    project text NOT NULL,
    stage bigint NOT NULL,
    level bigint NOT NULL DEFAULT 0,
    score double precision NOT NULL DEFAULT 0,
    inputs text NOT NULL DEFAULT '{}',
    sample_runs bigint NOT NULL DEFAULT 0,
    clawback_at double precision,
    computed_at double precision NOT NULL,
    PRIMARY KEY (workspace_id, project, stage)
);

CREATE TABLE IF NOT EXISTS decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL DEFAULT 'gate',
    status text NOT NULL DEFAULT 'active',
    scope text NOT NULL DEFAULT 'job',
    job_id text NOT NULL DEFAULT '',
    workspace_id bigint,
    project text NOT NULL DEFAULT '',
    stage bigint,
    title text NOT NULL DEFAULT '',
    text text NOT NULL,
    decided_by text NOT NULL DEFAULT '',
    origin_author text NOT NULL DEFAULT '',
    links text NOT NULL DEFAULT '[]',
    ref text NOT NULL DEFAULT '',
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL,
    updated_by text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS frictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    workspace_id bigint,
    project text NOT NULL DEFAULT '',
    stage bigint,
    source text NOT NULL,
    text text NOT NULL,
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS gate_chat (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    stage bigint NOT NULL,
    attempt bigint NOT NULL DEFAULT 1,
    role text NOT NULL,
    text text NOT NULL,
    cost_usd double precision,
    num_turns bigint,
    duration_ms double precision,
    session_id text DEFAULT '',
    degraded bigint NOT NULL DEFAULT 0,
    lane text NOT NULL DEFAULT '',
    at double precision NOT NULL,
    author text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gate_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    stage bigint,
    kind text NOT NULL,
    ref text NOT NULL,
    detail text DEFAULT '',
    actor text DEFAULT '',
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS guidance_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    stage bigint,
    action text NOT NULL,
    text text DEFAULT '',
    via text DEFAULT '',
    artifact_sha text DEFAULT '',
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS inbox_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint,
    kind text NOT NULL,
    source text NOT NULL DEFAULT '',
    dedupe_key text NOT NULL,
    source_sig text NOT NULL DEFAULT '',
    title text NOT NULL,
    body text NOT NULL DEFAULT '',
    refs text NOT NULL DEFAULT '{}',
    status text NOT NULL DEFAULT 'open',
    status_by text NOT NULL DEFAULT '',
    status_at double precision,
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
    issue_id text,
    kind text NOT NULL DEFAULT 'sentry',
    project text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    issue_url text DEFAULT '',
    status text NOT NULL,
    phase bigint NOT NULL DEFAULT 1,
    stage bigint NOT NULL DEFAULT 0,
    stage_attempts bigint NOT NULL DEFAULT 0,
    forced bigint NOT NULL DEFAULT 0,
    source text NOT NULL DEFAULT 'webhook',
    score double precision,
    grade_reasons text,
    request text DEFAULT '',
    analysis text,
    question text DEFAULT '',
    evidence text DEFAULT '',
    guidance text,
    owner text DEFAULT '',
    founder_dri text DEFAULT '',
    dev_dri text DEFAULT '',
    related_jobs text DEFAULT '',
    mirror_ok bigint NOT NULL DEFAULT 1,
    cu_list_id text DEFAULT '',
    clickup_task_id text,
    clickup_task_url text,
    comment_marker text DEFAULT '',
    parked_head text DEFAULT '',
    pending_redo_stage bigint,
    resume_session_id text DEFAULT '',
    resume_stage bigint,
    resume_attempt bigint,
    resume_head text DEFAULT '',
    resume_answer text DEFAULT '',
    gate_kind text DEFAULT '',
    ask_count bigint NOT NULL DEFAULT 0,
    gate_mode text NOT NULL DEFAULT 'full',
    pr_url text,
    detail text,
    attempts bigint NOT NULL DEFAULT 0,
    run_started_at double precision,
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL,
    steer_note text DEFAULT '',
    auto_retries bigint NOT NULL DEFAULT 0,
    workspace_id bigint,
    branch text NOT NULL DEFAULT '',
    success_metric text DEFAULT '',
    metric_target text DEFAULT '',
    metric_window_days bigint,
    metric_event text DEFAULT '',
    watch_started_at double precision,
    watch_deadline double precision,
    culprit text DEFAULT '',
    budget_override bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (issue_id)
);

CREATE TABLE IF NOT EXISTS metric_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    metric text NOT NULL DEFAULT '',
    metric_event text NOT NULL DEFAULT '',
    observed double precision,
    window_day bigint,
    window_start double precision,
    detail text NOT NULL DEFAULT '',
    at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL UNIQUE,
    feature_id text NOT NULL DEFAULT '',
    workspace_id bigint,
    metric text NOT NULL DEFAULT '',
    metric_event text NOT NULL DEFAULT '',
    target text NOT NULL DEFAULT '',
    observed double precision,
    baseline double precision,
    window_days bigint,
    verdict text NOT NULL DEFAULT '',
    verdict_inputs text NOT NULL DEFAULT '{}',
    learning text NOT NULL DEFAULT '',
    decided_by text NOT NULL DEFAULT '',
    decided_at double precision,
    created_at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS people (
    user_id bigint,
    person_role text NOT NULL DEFAULT '',
    areas text NOT NULL DEFAULT '[]',
    authority text NOT NULL DEFAULT '[]',
    notes text NOT NULL DEFAULT '',
    updated_at double precision NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS prs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    url text NOT NULL UNIQUE,
    repo text NOT NULL DEFAULT '',
    number bigint,
    state text NOT NULL DEFAULT 'draft',
    review_rounds bigint NOT NULL DEFAULT 0,
    last_checked double precision,
    detail text DEFAULT '',
    approved_head text NOT NULL DEFAULT '',
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id bigint NOT NULL,
    kind text NOT NULL,
    workspace_id bigint,
    started_at double precision NOT NULL,
    ended_at double precision,
    status text NOT NULL DEFAULT '',
    detail text NOT NULL DEFAULT '',
    items_emitted bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS routines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint,
    kind text NOT NULL,
    name text NOT NULL DEFAULT '',
    schedule text NOT NULL,
    config text NOT NULL DEFAULT '{}',
    enabled bigint NOT NULL DEFAULT 1,
    last_run_at double precision,
    last_status text NOT NULL DEFAULT '',
    last_result text NOT NULL DEFAULT '',
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS slack_cursors (
    channel text,
    last_ts text NOT NULL DEFAULT '0',
    updated_at double precision NOT NULL,
    PRIMARY KEY (channel)
);

CREATE TABLE IF NOT EXISTS stage_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL,
    stage bigint NOT NULL,
    attempt bigint NOT NULL DEFAULT 1,
    queued_at double precision,
    started_at double precision,
    ended_at double precision,
    gate_posted_at double precision,
    gate_answered_at double precision,
    gate_action text DEFAULT '',
    cost_usd double precision,
    num_turns bigint,
    duration_ms double precision,
    result_status text DEFAULT '',
    session_id text DEFAULT '',
    resumed bigint NOT NULL DEFAULT 0,
    transcript text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS stage_state (
    job_id text NOT NULL,
    stage bigint NOT NULL,
    base_sha text DEFAULT '',
    attempts bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (job_id, stage)
);

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    pw_hash text NOT NULL,
    role text NOT NULL DEFAULT 'member',
    clickup_user_id text NOT NULL DEFAULT '',
    disabled bigint NOT NULL DEFAULT 0,
    must_change_pw bigint NOT NULL DEFAULT 0,
    failed_attempts bigint NOT NULL DEFAULT 0,
    locked_until double precision,
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL,
    auth_provider text NOT NULL DEFAULT 'local',
    external_id text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS workspace_members (
    workspace_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role text NOT NULL DEFAULT 'member',
    repos text NOT NULL DEFAULT '[]',
    PRIMARY KEY (workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS workspace_repos (
    workspace_id bigint NOT NULL,
    slug text NOT NULL,
    repo text NOT NULL,
    base text NOT NULL DEFAULT 'main',
    setup_cmd text,
    test_cmd text,
    allow text NOT NULL DEFAULT '[]',
    PRIMARY KEY (workspace_id, slug)
);

CREATE TABLE IF NOT EXISTS workspaces (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    product_name text NOT NULL DEFAULT '',
    workspace_context text NOT NULL DEFAULT '',
    canonical_project text NOT NULL DEFAULT '',
    clickup_list_id text NOT NULL DEFAULT '',
    clickup_enabled bigint NOT NULL DEFAULT 0,
    slack_webhook_url text NOT NULL DEFAULT '',
    gate_mode_default text NOT NULL DEFAULT 'full',
    require_attributed_answers text NOT NULL DEFAULT 'auto',
    stage_role_map text NOT NULL DEFAULT '',
    gate_sla_hours bigint,
    created_at double precision NOT NULL,
    updated_at double precision NOT NULL,
    analytics_provider text NOT NULL DEFAULT '',
    analytics_config text NOT NULL DEFAULT '{}',
    slack_channels text NOT NULL DEFAULT '',
    budget_monthly_usd double precision
);

CREATE INDEX idx_api_tokens_user ON api_tokens(user_id);
CREATE INDEX idx_audit_ws ON audit_log(workspace_id, id);
CREATE INDEX idx_autonomy_events_ws_at ON autonomy_events(workspace_id, at);
CREATE UNIQUE INDEX idx_decisions_ref ON decisions(source, ref) WHERE ref != '';
CREATE UNIQUE INDEX idx_gate_events_dedupe ON gate_events(job_id, kind, ref);
CREATE UNIQUE INDEX idx_inbox_items_dedupe ON inbox_items(kind, dedupe_key);
CREATE UNIQUE INDEX idx_routines_scope
    ON routines(kind, COALESCE(workspace_id, -1));
CREATE UNIQUE INDEX idx_users_clickup_id
                         ON users(clickup_user_id) WHERE clickup_user_id != '';
CREATE UNIQUE INDEX idx_users_external_id
                         ON users(auth_provider, external_id) WHERE external_id != '';
CREATE UNIQUE INDEX idx_workspace_repos_slug ON workspace_repos(slug);
"""


def upgrade():
    op.execute(BASELINE_DDL)
    # one-shot data steps that the SQLite bootstrap runs in JobStore.__init__:
    op.execute("UPDATE users SET role='instance_admin' WHERE role='admin'")
    # legacy admin_events -> audit_log copy is gated on the same durable marker
    # so it never re-copies; on a fresh Postgres DB both tables are empty, so the
    # marker is simply planted.
    op.execute(
        "INSERT INTO app_config (key, value, updated_at) "
        "VALUES ('audit_legacy_copied', '1', extract(epoch from now())) "
        "ON CONFLICT (key) DO NOTHING")


def downgrade():
    raise NotImplementedError("baseline is not reversible")

