#!/usr/bin/env python3
"""Generate the Alembic Postgres baseline (Epic F1) WITHOUT data loss.

This codebase has NO SQLAlchemy models, so "autogenerated from the current
schema" means: build a throwaway SQLite JobStore (so SCHEMA + every MIGRATIONS
column + all indexes are applied exactly as production would apply them),
introspect ``sqlite_master`` + ``PRAGMA table_info``, and emit an equivalent
Postgres DDL revision.

Type translation:
    INTEGER                         -> bigint
    INTEGER PRIMARY KEY AUTOINCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY
    REAL                            -> double precision
    TEXT / other                    -> text
INTEGER-as-bool columns stay integer-class (bigint) — no boolean coercion.

The FTS5 virtual table ``mem_fts`` is SQLite-only and is intentionally NOT
emitted: Postgres FTS (tsvector) is out of scope for F1, so retrieval degrades
to absent there exactly like a SQLite build without FTS5.

Usage:  python scripts/gen_pg_baseline.py > migrations/versions/0001_baseline.py
The committed 0001_baseline.py is the output of this script — regenerate it
whenever a new MIGRATIONS column lands, and add the matching future revision.
"""

import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db import JobStore  # noqa: E402


def _pg_type(sqlite_type: str) -> str:
    t = (sqlite_type or "").upper().strip()
    if t.startswith("INT"):
        return "bigint"
    if t.startswith("REAL") or t.startswith("DOUB") or t.startswith("FLOA"):
        return "double precision"
    return "text"


def _col_fragments(create_sql: str) -> dict[str, str]:
    """Map each column name -> its DDL fragment from the CREATE TABLE body, so
    column-level UNIQUE (which SQLite hides behind a NULL-sql autoindex) is
    recoverable. Splits the parenthesized body on top-level commas."""
    if not create_sql:
        return {}
    body = create_sql[create_sql.index("(") + 1: create_sql.rindex(")")]
    frags, depth, cur = [], 0, []
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            frags.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        frags.append("".join(cur).strip())
    out = {}
    for f in frags:
        tok = f.split()
        if tok and tok[0].upper() not in ("PRIMARY", "UNIQUE", "FOREIGN", "CHECK", "CONSTRAINT"):
            out[tok[0].strip('"')] = f
    return out


def _column_ddl(col: dict, autoinc_pk: str | None, fragment: str) -> str:
    name = col["name"]
    if name == autoinc_pk:
        # single-column INTEGER PRIMARY KEY AUTOINCREMENT -> identity PK
        return f"{name} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    parts = [name, _pg_type(col["type"])]
    if col["notnull"]:
        parts.append("NOT NULL")
    if col["dflt_value"] is not None:
        parts.append(f"DEFAULT {col['dflt_value']}")
    if "UNIQUE" in (fragment or "").upper():
        parts.append("UNIQUE")
    return " ".join(parts)


def _emit():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    try:
        store = JobStore(path)
        with store._conn() as c:
            tables = [
                r["name"] for r in c.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' "
                    "AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
            ]
            create_sql = {
                r["name"]: r["sql"] for r in c.execute(
                    "SELECT name, sql FROM sqlite_master WHERE type='table'").fetchall()
            }
            table_ddls = []
            for t in tables:
                if t.startswith("mem_fts"):  # FTS5 virtual — SQLite-only
                    continue
                info = [dict(r) for r in c.execute(f"PRAGMA table_info({t})").fetchall()]
                raw = create_sql.get(t) or ""
                frags = _col_fragments(raw)
                sql = raw.upper()
                # single-column autoincrement PK?
                autoinc_pk = None
                pk_cols = [col["name"] for col in info if col["pk"]]
                if len(pk_cols) == 1 and "AUTOINCREMENT" in sql:
                    autoinc_pk = pk_cols[0]
                cols = [_column_ddl(col, autoinc_pk, frags.get(col["name"], "")) for col in info]
                if len(pk_cols) >= 1 and autoinc_pk is None:
                    # composite PK order follows PRAGMA's pk index
                    ordered = [col["name"] for col in sorted(info, key=lambda x: x["pk"]) if col["pk"]]
                    cols.append(f"PRIMARY KEY ({', '.join(ordered)})")
                body = ",\n    ".join(cols)
                table_ddls.append(f'CREATE TABLE IF NOT EXISTS {t} (\n    {body}\n);')

            # indexes (partial WHERE + COALESCE expression indexes are valid in PG)
            index_ddls = []
            for r in c.execute(
                "SELECT name, sql FROM sqlite_master WHERE type='index' "
                "AND sql IS NOT NULL ORDER BY name").fetchall():
                idx_sql = r["sql"]
                if idx_sql and "mem_fts" not in idx_sql:
                    index_ddls.append(idx_sql.rstrip(";") + ";")
    finally:
        os.unlink(path)

    ddl = "\n\n".join(table_ddls) + "\n\n" + "\n".join(index_ddls)
    print(_REVISION_TEMPLATE.format(ddl=ddl))


_REVISION_TEMPLATE = '''"""baseline schema (Epic F1) — generated by scripts/gen_pg_baseline.py

Materializes the EXACT current effective SQLite schema (SCHEMA + every
MIGRATIONS column + all indexes) as equivalent Postgres DDL. Regenerate with
scripts/gen_pg_baseline.py whenever a MIGRATIONS column is added; add the
matching future revision (never edit this baseline in place after first ship).

The FTS5 mem_fts virtual table is intentionally absent — Postgres retrieval
degrades to absent (fts_enabled=False), out of scope for F1.

Revision ID: 0001_baseline
Revises:
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

BASELINE_DDL = """
{ddl}
"""


def upgrade():
    op.execute(BASELINE_DDL)
    # one-shot data steps that the SQLite bootstrap runs in JobStore.__init__:
    op.execute("UPDATE users SET role='instance_admin' WHERE role='admin'")
    # legacy admin_events -> audit_log copy is gated on the same durable marker
    # so it never re-copies; on a fresh Postgres DB both tables are empty, so the
    # marker is simply planted.
    op.execute(
        "INSERT INTO app_config (key, value, updated_at) "
        "VALUES ('audit_legacy_copied', '1', extract(epoch from now())) "
        "ON CONFLICT (key) DO NOTHING")


def downgrade():
    raise NotImplementedError("baseline is not reversible")
'''


if __name__ == "__main__":
    _emit()
